sudo: required
services:
  - docker

before_install:
  - docker build -t mateorh/react-test -f ./client/Dockerfile.dev ./client

script:
  # exit test when finishes
  - docker run -e CI=true mateorh/react-test npm test

after_success:
  - docker build -t mateorh/multi-client ./client
  - docker build -t mateorh/multi-nginx ./nginx
  - docker build -t mateorh/multi-server ./server
  - docker build -t mateorh/multi-worker ./worker
  # Take those images and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mateorh/multi-client
  - docker push mateorh/multi-nginx
  - docker push mateorh/multi-server
  - docker push mateorh/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-016302829356
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
